<h1><?=$this->title?></h1>
<table class="indexTable">
	<tr>
		<th>gebruiker</th>
		<th>email</th>
		<th>bewerkingen</th>
	</tr>
	<?php foreach ($this->users as $user): ?>
		<tr>
			<td>
				<?=$user->voornaam . ' ' . $user->tussenvoegsel . ' ' . $user->achternaam?>
			</td>
			<td>
				<?=$user->email?>
			</td>
			<td class="actions">
				<a href="/user/edit/id/<?=$user->id?>">bewerk</a>
				<a href="/user/delete/id/<?=$user->id?>"  class="confirm" data:confirmation="Wilt u user <?=strtoupper($user->getFullName())?> echt verwijderen?">verwijder</a>
			</td>
		</tr>
	<?php endforeach ?>
</table>
